### PR TITLE
don't expect parser to always succeeed. Fixes #113

### LINKED ISSUE #113: When files are removed from the directory during uploads, the app completely breaks.
Since the replay file statuses are kept in a database, if you remove the replay files between the time that it was added as an upload task and the time it was successfully uploaded, you will get constantly get *Connection Error*.

Example of the log:
```
17:28:39.761 [pool-2-thread-1          ] INFO  n.e.h.concurrent.tasks.UploadTask - Uploading replay Garden of Terror (5).StormReplay
17:28:39.761 [JavaFX Application Thread] WARN  n.e.h.models.ReplayFile - Infernal Shrines (3).StormReplay has no statuses.
17:28:39.762 [JavaFX Application Thread] ERROR n.e.h.services.UploaderService - UploadTask failed.
ninja.eivind.mpq.models.MpqException: Could not parse file
	at ninja.eivind.stormparser.StormParser.parseReplay(StormParser.java:33) ~[storm-parser-0.1.1.jar:na]
	at ninja.eivind.hotsreplayuploader.concurrent.tasks.UploadTask.lambda$call$49(UploadTask.java:48) ~[HotS%20Replay%20Uploader-jfx.jar:2.0.3]
	at java.util.Collections$SingletonList.forEach(Collections.java:4822) ~[na:1.8.0_60]
	at ninja.eivind.hotsreplayuploader.concurrent.tasks.UploadTask.call(UploadTask.java:45) ~[HotS%20Replay%20Uploader-jfx.jar:2.0.3]
	at ninja.eivind.hotsreplayuploader.concurrent.tasks.UploadTask.call(UploadTask.java:32) ~[HotS%20Replay%20Uploader-jfx.jar:2.0.3]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
	at javafx.concurrent.Service.lambda$null$493(Service.java:725) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
	at javafx.concurrent.Service.lambda$executeTask$494(Service.java:724) ~[jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.io.FileNotFoundException: /Users/moox/Library/Application Support/Blizzard/Heroes of the Storm/Accounts/56880185/1-Hero-1-5311518/Replays/Multiplayer/Garden of Terror (5).StormReplay (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_60]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_60]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_60]
	at ninja.eivind.mpq.MpqArchive.getFiles(MpqArchive.java:53) ~[mpq-exploder-0.1.1.jar:na]
	at ninja.eivind.stormparser.StormParser.parseReplay(StormParser.java:29) ~[storm-parser-0.1.1.jar:na]
	... 12 common frames omitted
```

Deleting the database file fixes the issue.

### PR DESCRIPTION
**Pull request by eivindveg**
This pull request fixes #113

### CODE REVIEW

**Comment by zhedar** [comment]
When setting the replay to new again on a failed attempt and the file was removed, does the uploader still try to upload it, failing everytime to do so, since the file is absent?
Because I can only remember, that we remove missing files on application startup.
I guess it's not added to the upload queue?

**Comment by eivindveg** [comment]
You're right. It should be EXCEPTION, and the service should check if the taken file exists before submitting it to a task, deleting it otherwise.

**Comment by zhedar** [comment]
That sounds sane to me, introducing an upload loop of horror wouldn't be so kind I guess :D

File: src/main/java/ninja/eivind/hotsreplayuploader/concurrent/tasks/UploadTask.java [hunk 1]
```diff
@@ -53,9 +53,12 @@ protected ReplayFile call() throws Exception {
...
             } catch (MpqException e) {
                 LOG.warn("Could not parse replay, deferring to upload." + take, e);
-                preStatus = Status.NEW;
+
+                preStatus = Status.EXCEPTION;
             }
-            if (preStatus == Status.UPLOADED || preStatus == Status.UNSUPPORTED_GAME_MODE) {
+            if (preStatus == Status.UPLOADED ||
+                preStatus == Status.UNSUPPORTED_GAME_MODE ||
+                preStatus == Status.EXCEPTION) {
```
Comment (eivindveg) [inline src/main/java/ninja/eivind/hotsreplayuploader/concurrent/tasks/UploadTask.java]: This will permanently break all files we cannot parse, which would be unfortunate if the protocol is updated and I haven't updated my parser.

Comment (zhedar) [inline src/main/java/ninja/eivind/hotsreplayuploader/concurrent/tasks/UploadTask.java]: So you upload games, if they failed to parse as well?

Comment (eivindveg) [inline src/main/java/ninja/eivind/hotsreplayuploader/concurrent/tasks/UploadTask.java]: Aye. We don't want to discard replays that @barrett777 might be able to parse in case the protocol changes and this app is abandoned. That would break it permanently.

Comment (zhedar) [inline src/main/java/ninja/eivind/hotsreplayuploader/concurrent/tasks/UploadTask.java]: I initially put that in, because the upload of a non-existent file caused some exception on the upload. But a simple file existence check in the service will do as well.
